# Generated by Django 3.2.2 on 2021-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komik',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
