# Generated by Django 3.2.2 on 2021-05-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_komik_jumlah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='komik',
            name='id_negara',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.negara'),
        ),
    ]
